version: '3.4'
services:
  app:
    env_file: ./.docker/.env
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 3101:3100
    volumes:
      - .:/app
    command: npm run start:dev
    